version: 0.0
os: linux
permissions:
  - object: /home/ubuntu/www
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
      - location: scripts/start_docker.sh
        timeout: 300
        runas: ubuntu